### ISSUE TITLE
Ethnicity Choices are Confusing

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#11]
@radhikajain @ecd25 Let's have this conversation here, rather than in a closed PR, ok?

**Comment by radhikajain** [comment]
Right, I know you told me I can add more categories in django anytime. Which is why I don’t think it’s worth the time to figure out options + fill in other unless it will be useful for other questions, since we can easily add in another ethnicity after
 clinic and update the person’s profile. 


I guess I will look up the top ten ethnicities in STL and put them in instead.

**Comment by justinrporter** [comment]
Ok! Great! That would be awesome. Thank! Sorry for being dense. :grimacing:

>  I can add more categories in django anytime

Right! I see what the confusion is now, so let me take the chance to do a little education: when we say something is "hard-coded" it means it's not possible to change without editing the source code for whatever program you're using. So, for example, it's currently hard-coded that whenever you write a workup, it is applied to that day. I would have to change stuff in the code to allow something else. Does that make sense?

**Comment by radhikajain** [comment]
Got it. Good check, thanks for the explanation

**Comment by justinrporter** [comment]
@radhikajain so I'm waiting on you for the ethnicities, right?

**Comment by radhikajain** [comment]
Yes I suppose so I’m sorry I probably won’t get to it until later today…

**Comment by justinrporter** [comment]
No problem! I am not blocked from making progress by this right now. :stuck_out_tongue:

**Comment by radhikajain** [comment]
I just did it… not enjoying work today. 




I can guess ethnicities based on the wikipedia page information on population pockets, but the most credible information close to ethnicity I can find is 




http://quickfacts.census.gov/qfd/states/29/29189.html



And http://dynamic.stlouis-mo.gov/census/city.cfm


And these are race-based, not ethnicity. Davis, did you have a source in mind to find the top-ten ethnicities? 


Maybe the better option is what you originally suggested, use the top ten ethnicities that have come through SNHC so far. The issue we need to clarify is that “White” or “Caucasian” or “Hispanic” is not an Ethnicity, and if we want to stay true to that
 classification then I think we have to be specific on the intake form, like, “What is your country of origin.” If we’re comfortable lumping people into White/Black/Hispanic/Asian then we’d be more accurate to call it ‘Race’.

**Comment by justinrporter** [comment]
I think that's a really good distinction to make. Medically, we like to track race, since there are different risk factors for some conditions. Demographically, we might like to track country of origin.

I think a discussion with Derek might be in order...

**Comment by radhikajain** [comment]
Davis, can you please coordinate that discussion with Derek, maybe start an email thread with all of us on it so that there's no confusion? Ideally we'd loop him into this conversation but I don't know if he knows how to use github.

**Comment by justinrporter** [comment]
I will get derek up and running with github.

**Comment by ecd25** [comment]
I just got all of these!! We are having another small storm make the connection bad. I'm happy to send out a nice group email though. 

I'm still happy to make it simple and have ethnicity be a fill in your own blank though since what we want from that question is diversity.

Race is useful for medical info and for  grants, but I'm not sure we would be using it, probably it will come out in the histories.

**Comment by justinrporter** [comment]
So, the key is to think about how we will want to retrieve the information later. A fill-in-the-blank will give us people who enter "African American", "african american", "african-american", and "AA" (or... is this an ethnicity or a race? Whatever. I'm still confused about this.). It will be then very difficult to count how many african american patients we've served, since somebody has to go in *ex post facto* and categorize anything, which is pretty lame.

Ditto for relying on histories to provide race data--if we don't have people classify at the point of care, we will have to go back in and process it later which, from my perspective as a CS guy, is super lame.

**Comment by radhikajain** [comment]
Exactly. I think administrators can serve as the “fill in the blank” function so as to maintain standardized categorizations. I think, Davis, this will become way clearer once you actually see how the EMR is handled from the backend <— I hope this is correct
 usage of the vocabulary, Justin.

**Comment by justinrporter** [comment]
@dtst42 want to weigh in on this?

**Comment by dtst42** [comment]
Ethnicity: What is the point in getting this information? I think that race is important for demographic purposes, but I'm not sure that knowing which culture people identify with is too important. I think that language tracking is more important than this. I vote that we do not track ethnicity.

Race: Important for demographic purposes.

Language: This is important and related to ethnicity. I also think it is much more important than ethnicity.

**Comment by justinrporter** [comment]
So, a detail of implementation: do we want to take race on intake or as part of the additional demographics entry process?

**Comment by radhikajain** [comment]
intake

**Comment by justinrporter** [comment]
What is the status of this? Did we decide that the current list is fine?

**Comment by ecd25** [comment]
I'd still like to leave it as fill in your own. It won't take that much longer to get data from it.

**Comment by justinrporter** [comment]
We can talk about this at the board meeting but would urge strongly against free text where multiple choice is possible. Because while we can all agree that "Black", "black", and "balck" are probably the same, there is a subtle difference between "black" and "african american" that is not necessarily straightforward to tease out *ex post facto*.

**Comment by dtst42** [comment]
I agree with Justin.


________________________________

**Comment by Talophex** [comment]
I also agree with Derek and Justin and additionally fail to see how 'country of origin' and 'ethnicity' merit separate data fields.

Lucas

**Comment by justinrporter** [comment]
@dtst42  this on you to categorize appropriately through the admin panel on the deployed version.

**Comment by dtst42** [comment]
I want to just recode everything to this system which I got from the National Center for Education Statistics. The new categories would be:


Hispanic or Latino

American Indian or Alaska Native

Asian

Black or African American

Native Hawaiian or Other Pacific Islander

White


Just wanted to put this out there for you all to see before going forward with changing this in the website. If I don't hear complaints about this, I will try to figure out how to update the website later this week.

-Derek

________________________________

**Comment by radhikajain** [comment]
I think it's a good idea.

**Comment by justinrporter** [comment]
Ok. @dtst42  that sound great. You should be able to do this from the admin panel.

**Comment by dtst42** [comment]
Sounds good. Thank you.


________________________________

**Comment by nakul2234** [comment]
Change is already in live osler
