### ISSUE TITLE
Collapse of menu bar

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#12]
When the viewport has an aspect ratio appropriate for mobile, the navbar is uncollapsable. Should be fixable in angular in pttrack/base.html

Perhaps we could also completely remove angular dependency and go with only [Bootstrap](http://getbootstrap.com) + [jQuery](http://jquery.com/).

**Comment by justinrporter** [comment]
Now with the tablets we really need to fix this...

**Comment by nakul2234** [comment]
#96
