### ISSUE TITLE
Height & Weight-Decimals

### ISSUE THREAD

**Issue by daminitandon** [SaturdayNeighborhoodHealthClinic/osler#127]
Height and weight are required to be whole numbers in order to submit the write-up. 
1) This requirement is not made clear; when the write-up is not submitting due to this error, the error is not stated for the user to see. If nothing else, let's make this error visible to the user. 
2) We are losing data with this error, so it would be nice for us to remove this requirement.

**Comment by justinrporter** [comment]
Wow this is annoying. I will investigate.

**Comment by JoLBree** [comment]
I'm wondering if it might be linked to the thing about the numbers not being visible, I'll take a look

**Comment by nakul2234** [comment]
#133
