### ISSUE TITLE
Active Items/Active Patients

### ISSUE THREAD

**Issue by daminitandon** [SaturdayNeighborhoodHealthClinic/osler#128]
On Saturday 8/6/16, the clinicals didn't see active patients under the active patients list; instead, they see all of the patients to whom the active action items correspond. This makes it difficult for them to find the active patients that they are seeing/creating write-up.

**Comment by justinrporter** [comment]
@JoLBree do you think this has to do with the home page redo? Could you look in to this?

**Comment by justinrporter** [comment]
Bug reproduced in #136 .

**Comment by justinrporter** [comment]
Fixed in #136
