### ISSUE TITLE
edit workup note

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/osler#18]
add checkboxes for documents given to patients

like "got voucher"

"got prescription"
"got instruction sheet"
etc

**Comment by nakul2234** [comment]
Do we still want to do this in the EMR, or should we just rely on the flow charts that were suggested in the last meeting?

**Comment by ecd25** [comment]
If we have to choose one, or the order, I'd prefer we go with the time
stamps of when they are taken from the waiting room and when they see a
doctor/get labs/get discharged

This is important for volunteers to recall, but I don't think it needs to
be a role in Osler.

On Wed, Nov 18, 2015 at 6:37 PM, Nakul Shah <notifications@github.com>
wrote:

> Do we still want to do this in the EMR, or should we just rely on the flow
> charts that were suggested in the last meeting?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SaturdayNeighborhoodHealthClinic/osler/issues/18#issuecomment-157909679>
> .
>



-- 
Emily Davis

Washington University School of Medicine
Class of 2018

Cell Phone: (818) 523 7003
Email: emilychristinedavis@gmail.com

**Comment by nakul2234** [comment]
I think this should be a checklist that is a physical paper one or part of the timeline. It is probably not a good idea for teams to write a workup note, and then not submitting it because of a few checkboxes not being filled. This can lead to data loss as we have seen before.
