### ISSUE TITLE
Demographics Clash - submitting new demographics object when one already exists

### ISSUE THREAD

**Issue by ameller1994** [SaturdayNeighborhoodHealthClinic/osler#196]
Though I thought we had solved this problem, it appears that submitting a new demographics object throws an error (`The requested URL /demographics/1180/update/ was not found on this server.`). When you try to submit a new demographics object, Osler will take you to the demographics clash form. However, from there you are unable to submit your selected corrected form.

**Comment by justinrporter** [comment]
Can't replicate--it looks like this patient was some kind of odd duplicate type situation.
