### ISSUE TITLE
Is Grace Hill missing from the referral locations?

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#21]
Sagar and I couldn't find it last weekend. You'll have to download the [VPN](https://msvpn.wusm.wustl.edu) and then go to pttrack.snhc.wustl.edu and use the admin panel to add it.

**Comment by radhikajain** [comment]
Is Affinia on the list? Grace Hill is technically now Affinia.

From: <Jain>, Radhika <radhikajain@wustl.edu<mailto:radhikajain@wustl.edu>>
Date: Sunday, September 6, 2015 at 10:04 AM
To: SaturdayNeighborhoodHealthClinic/osler <reply@reply.github.com<mailto:reply@reply.github.com>>, SaturdayNeighborhoodHealthClinic/osler <osler@noreply.github.com<mailto:osler@noreply.github.com>>
Subject: Re: [osler] Is Grace Hill missing from the referral locations? (#21)

it's telling me vpn page is not available :/

**Comment by radhikajain** [comment]
it's telling me vpn page is not available :/

**Comment by justinrporter** [comment]
Oops! Try again. Affinia probably is... the question then becomes how do we deal with people not being able to find it? A lazy dynamic search field would probably be the best but that feature is a ways down the road...

**Comment by radhikajain** [comment]
Still not working :/

ALSO, Davis and I have given you time on Tuesday after board introductions to get everyone onto github so they can access the wiki. Is there anything we can make them do in advance to speed up the process?

Do we want to make them coordinators on the EMR as well, since they'll be running the show in a few weeks anyway, or wait until the following Tuesday when we actually delve into the EMR?

**Comment by justinrporter** [comment]
Honestly, I don't like the wiki setup we have. I want to try to integrate a into the EMR more fully so that there's only one login and so that non-coordinators can view at the clinic.

Can you send me a picture per email of "not working"?

**Comment by radhikajain** [comment]
Oh noo but I need them on the wiki asap so they know that's their main coordinating resource!! On a scale of 1-10, how annoying would it be to get them github right now to access wiki and then integrate later?

[cid:832326FD-E970-4440-9ABD-45585145F126]

**Comment by justinrporter** [comment]
Ok, so if "Affinia" = Grace Hill, could we add "(Grace Hill)" to the name of Affinia in the admin panel?

**Comment by radhikajain** [comment]
Yes definitely

**Comment by justinrporter** [comment]
Fantastic.
