### ISSUE TITLE
Titles in Django

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/osler#33]
For example, I need to update an action item in the admin panel, but all the action items look the same so it's hard to find the one I need without clicking them all. 

AI: PCP follow up
AI: PCP follow up
AI: lab follow up

Any way to have a little more identifying information on there?

**Comment by justinrporter** [comment]
Fixed in d3aa6f8b822c164f440b9bc55156fa7821276078.
