### ISSUE TITLE
phone numbers in patient information section

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/osler#39]
We can enter multiple phone numbers into the patient chart but only see one when we go to make phone calls

**Comment by justinrporter** [comment]
@nakul2234 this is probably because the template for the patient is custom-generated and we don't populate it with the alternative phone fields...

**Comment by justinrporter** [comment]
Addressed by 15ed67e6c9ffd335d5d6627ecf44c4d2ba0f5cd5
