### ISSUE TITLE
follow up editing

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/osler#52]
@justinrporter, @nakul2234, Davis and I were talking about how to optimize follow up documentation. How do you feel about having a single follow up type with different sections for vaccines, labs, PCP, and other so that a single phone call (with multiple topics) can be logged in a single follow up note. These sections would not be required but still have the same drop down menus that we've created to support standardization of answers.

This is more of a long-term change, not necessarily urgent, but may improve tracking (can see number of phone calls based on number of follow ups) and also let you include all the content from a single phone call in one follow up.

**Comment by justinrporter** [comment]
I totally agree that this change should be done. I think it will be a bit complicated, but I would very much like to get done, since I think it would clean things up dramatically. Nakul and will discuss implementation options.
