### ISSUE TITLE
String Comparisons on ProviderType

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#54]
This has been really bothering me.

There are a number of places in the code where we do things like:
```python
if active_provider_type.short_name == "Coordinator":
```
In fact, we should probably have a boolean in `ProviderType` for this purpose. We could use the `User.is_staff` property. Another way might be to use the `User` model/admin page's permissions groups (`Coordinator` is now a permissions group for accessing the admin panel and whatnot).

In any case, string comparison to the specific primary key for a provider type is a recipe for trouble.

**Comment by nakul2234** [comment]
#70
