### ISSUE TITLE
Language/Ethnicity Issue

### ISSUE THREAD

**Issue by nakul2234** [SaturdayNeighborhoodHealthClinic/osler#64]
It bothers the coordinators a lot and they mention it almost every week. We need to decide what to do about this soon

**Comment by justinrporter** [comment]
This would have been trivial to fix three months ago but it is getting more and more difficult as people use the existing ethnicities. @radhikajain 

I am tempted to remove it completely and then future data managers will simply be responsible for mining one-liners for this data if they want it.

**Comment by radhikajain** [comment]
I didn't realize it hadn't been resolved. I thought we decided to forgo ethnicity and only have the 5-6 major race classes?
Let's just get rid of it but keep some kind of language box so that we have a way of tracking people's preferred language.

**Comment by justinrporter** [comment]
+1 for ditching it completely. It's tracked in HPIs and kind of unclear if we need this information at all.

Language is a completely independant metric and, I think, important.

**Comment by radhikajain** [comment]
Alright, done, get rid of it.

**Comment by nakul2234** [comment]
I think if we want to keep the ethnicity, I will just add an "other" option. When people first create a patient and see this, they can select other. Then once they figure out the ethnicity, they can update it in our database using the Admin panel. Let's say we want to track this information in the future, I think it will be a pain to have deleted the variable completely, and then add it in and have to give a default ethnicity to all previous patients.

**Comment by justinrporter** [comment]
Sure. There is some discussion of building a full demographics questionnaire (read: app) that will track this stuff and more. That will require a proper migration, so I think that for now your strategy is good. 

Alternatively, you could add an extra field to the form where people could type their own, and it would add it to the options? In validation, you could require that Ethnicity be blank.

**Comment by nakul2234** [comment]
Actually I didn't even see that someone already changed the ethnicities to just being the following:
        White
	Native Hawaiian or Other Pacific Islander
	Hispanic or Latino
	Black or African American
	Asian
	American Indian or Alaska Native
Also the new patient form will have ethnicity. So I guess issue is solved now?

**Comment by justinrporter** [comment]
Huh. I wonder what happened to all the patients with already existing demographics?

**Comment by nakul2234** [comment]
I looked at a few patients from September, and they seem to have either defaulted to white or the person who made the change also made sure they got the right ethnicity asigned. I think it actually seems pretty accurate.

**Comment by justinrporter** [comment]
Cool. I guess we can double check with the one-liner to make sure everything is fine.
