### ISSUE TITLE
Adding the Edit option for action items the user created

### ISSUE THREAD

**Issue by nakul2234** [SaturdayNeighborhoodHealthClinic/osler#65]
Though now coordinators can change notes, the preclinicals/clinicals make mistakes often. I understand we do not want to give them edit power over our system, but on notes they create (and are not signed), maybe they should have the option to edit. Same with the action items.

**Comment by justinrporter** [comment]
Agreed. Now that we track the history of these models, I think allowing editing would be very reasonable.

**Comment by nakul2234** [comment]
I just need to create an update for action items. The other three notes (workup, upload, followup) you can click on the title and edit it.

**Comment by justinrporter** [comment]
Huh. Sounds like whoever did that wasn't so stupid, after all...

**Comment by nakul2234** [comment]
I mean, maybe...

**Comment by radhikajain** [comment]
:)

**Comment by nakul2234** [comment]
#70
