### ISSUE TITLE
Dealing with Active Patients from Previous Clinic Days

### ISSUE THREAD

**Issue by nakul2234** [SaturdayNeighborhoodHealthClinic/osler#68]
Some days, the attending ends up never signing the notes, and the patient remains active because Coordinators did not inactivate them since the attending has not gotten around to signing them yet. I was thinking of maybe making the active patients list by clinic date so people will not be confused when they see names from previous dates. Also, we need a way to make sure in a week those notes are signed. This may require talking to all the coordinators and having them remind their attending every couple of days so that we do not have a large backlog of unsigned notes.

**Comment by radhikajain** [comment]
Yess super important. We will make sure to bring this up at our last selective session.

**Comment by justinrporter** [comment]
Agreed.

As a longer term-fix, we need a richer representation of the clinical teams at each clinic day, as well as the ability to track who the attending signed up is, so that we can automatically email the attending(s) if there are outstanding patients.

**Comment by nakul2234** [comment]
Closing for now since we discussed it at the meeting and now coordinators know what to do about it.
