### ISSUE TITLE
add weight and height to EMR vital signs

### ISSUE THREAD

**Issue by radhikajain** [SaturdayNeighborhoodHealthClinic/osler#74]
weight in kg, i think
height in ... not sure

**Comment by nakul2234** [comment]
Should this be a part of the workup? Do the clinical teams still get the document where the patients report their height and weight?

**Comment by radhikajain** [comment]
patients don't report height and weight themselves, per se, but the clinical team collects this information with vitals so it should be part of the workup.

**Comment by nakul2234** [comment]
#96
