### ISSUE TITLE
More space in action items

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/osler#75]
In particular if it is a general action item (not vaccine or lab), I'd like to be able to put a full on paragraph of instructions if I so choose. Some things can be tricky and need explaining. I'm not sure what the limit is now, but its annoying that there is one and that it only lets you see one line of text at a time.

**Comment by nakul2234** [comment]
I think this should not be too difficult to do. I will try to fit this in with the current Pull Request I am working on.

**Comment by nakul2234** [comment]
#70

**Comment by ecd25** [comment]
Hey! I was still only able to get three lines of text in last time I tried (less than a week ago). It should be unlimited.

**Comment by nakul2234** [comment]
#84  deals with this further. By next week itll be ready
