### ISSUE TITLE
SSN required on PatientUpdate

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#81]
It seems SSN is required on the patient update view. This should not be the case.

**Comment by nakul2234** [comment]
Idk when, but this is not a problem

**Comment by justinrporter** [comment]
At least on the demo implementation, it is. Just go [here](http://oslerproject.org/pttrack/patient/update/5) and hit submit.

**Comment by justinrporter** [comment]
SSNs removed in #138
