### ISSUE TITLE
Demographics

### ISSUE THREAD

**Issue by ecd25** [SaturdayNeighborhoodHealthClinic/osler#83]
I just looked at the new patient entry form and there is no place for most of the new intake information (education, employment, etc.). I really want to make sure we have volunteers entering this demographic information online from day one so we can analyze it at next years grand rounds. I am worried about what happened to the intakes for the first two weeks - I think that data could be gone forever! If we can find those forms I'd be happy to update the patient charts for the past two weeks - I just don't want to lose it.

**Comment by radhikajain** [comment]
do we know what coordinators have been doing with the intake forms?

**Comment by ecd25** [comment]
I'm not sure- shred or give to FCHC?

**Comment by nakul2234** [comment]
Hello Guys,
I looked at the form and I found all of the fields that are not explicitly put into a category into Osler:
Address
Health Insurance
Chronic Conditions
ER in the last year?
Date of last Physician Visit
Do you live alone?
Number of dependents:
How did you get here today?
I currently have access to:
Are you working right now?
What best describes your work status?
What is your current level of schooling completed?
What is your annual income?

I could just add these as a tab in the workup form, or we could maybe make another survey document to have these values.
@justinrporter let me know if you have any thoughts on the organization of this information.

**Comment by ecd25** [comment]
Can these all show up when you enter a new patient? Not in the work-up?
(tabs or otherwise)

On Wed, Jan 20, 2016 at 3:35 PM, Nakul Shah <notifications@github.com>
wrote:

> Hello Guys,
> I looked at the form and I found all of the fields that are not explicitly
> put into a category into Osler:
> Address
> Health Insurance
> Chronic Conditions
> ER in the last year?
> Date of last Physician Visit
> Do you live alone?
> Number of dependents:
> How did you get here today?
> I currently have access to:
> Are you working right now?
> What best describes your work status?
> What is your current level of schooling completed?
> What is your annual income?
>
> I could just add these as a tab in the workup form, or we could maybe make
> another survey document to have these values.
> @justinrporter <https://github.com/justinrporter> let me know if you have
> any thoughts on the organization of this information.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SaturdayNeighborhoodHealthClinic/osler/issues/83#issuecomment-173366799>
> .
>



-- 
Emily Davis

Washington University School of Medicine
Class of 2018

Cell Phone: (818) 523 7003
Email: emilychristinedavis@gmail.com

**Comment by nakul2234** [comment]
Some of these things can change in between visits, but do we only wan to start tracking with new patients? If that is the case we can have it ready by next saturday. This saturday I can remind the coordinators to scan the forms in

**Comment by ecd25** [comment]
I think we just want one data point per patient for most of these. It should be editable if things change anyways right?

**Comment by nakul2234** [comment]
Yeah we can do that and incorporate it soon!

**Comment by nakul2234** [comment]
#88
