### ISSUE TITLE
Demographics Tracking

### ISSUE THREAD

**Issue by justinrporter** [SaturdayNeighborhoodHealthClinic/osler#9]
We also want to track demographics. This shouldn't be too hard once we have a datamodel in place. @radhikajain do you know what you want to track here?

**Comment by radhikajain** [comment]
Yep I have all the questions.

**Comment by justinrporter** [comment]
Could you post a link to them here?

**Comment by radhikajain** [comment]
Surely. For now, the “DEMOGRAPHICS” section on 
this form.

**Comment by radhikajain** [comment]
https://docs.google.com/forms/d/1wVEywrJ5Y2M7PgM9KBLQU_21zKwCOohJ6CGzLun0tOc/viewform?usp=send_form

**Comment by justinrporter** [comment]
Delicious. Thanks! We decided that is is a post-launch feature, right?

**Comment by radhikajain** [comment]
right

**Comment by nakul2234** [comment]
Patient demographics already switched to this list
