### ISSUE TITLE
Remove the redirect from the Patient Intake to the Demographics

### ISSUE THREAD

**Issue by nakul2234** [SaturdayNeighborhoodHealthClinic/osler#93]
The coordinators actually have the teams give this to the patients during the visit and it is not present at intake. Thus it does not make sense as a part of the intake form or to be right after the intake form.

**Comment by nakul2234** [comment]
I am going to leave it like this for now because I think maybe they should just get that information at the beginning.

**Comment by justinrporter** [comment]
Good question--why *don't* we get this info at intake?

**Comment by nakul2234** [comment]
This is done at intake. There is a needs assesment form that is given after which we also want to track as a note.
